# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-30 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='samend',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='samst',
        ),
    ]
