# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrecord',
            old_name='concentration',
            new_name='conc',
        ),
        migrations.RenameField(
            model_name='testrecord',
            old_name='sampleend',
            new_name='samend',
        ),
        migrations.RenameField(
            model_name='testrecord',
            old_name='samplestart',
            new_name='samst',
        ),
        migrations.RenameField(
            model_name='testrecord',
            old_name='testconcentration',
            new_name='testconc',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='boxnumber',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='samplename',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='samplenum',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='fromcpd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.cpd'),
        ),
    ]
