# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='samend',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='samst',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='testconc',
            field=models.FloatField(blank=True, default=12),
            preserve_default=False,
        ),
    ]
