# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181219_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudeex',
            name='chinesename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='entercol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='entervol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='mcccnumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='solvent',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
