# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-30 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181030_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='batch',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
