# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_testrecord_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='batch',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='conc',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='volume',
            field=models.FloatField(blank=True),
        ),
    ]
