# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20180301_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='bact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bactnumber', models.CharField(max_length=50)),
                ('sourcenum', models.CharField(max_length=50)),
                ('genus', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('chinesename', models.CharField(max_length=200)),
                ('othersourcenum', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=100)),
                ('storetimr', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='crudeex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crudenumber', models.CharField(max_length=50)),
                ('mcccnumber', models.CharField(max_length=50)),
                ('genus', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('chinesename', models.CharField(max_length=200)),
                ('media', models.CharField(max_length=200)),
                ('medianumber', models.CharField(max_length=50)),
                ('mass', models.FloatField()),
                ('stockmass', models.FloatField()),
                ('cointermass', models.FloatField()),
                ('entertime', models.DateTimeField()),
                ('entervol', models.FloatField()),
                ('entercol', models.FloatField()),
                ('tetscol', models.FloatField()),
                ('testvol', models.FloatField()),
                ('activecol', models.FloatField()),
                ('solvent', models.CharField(max_length=100)),
                ('culture', models.CharField(blank=True, max_length=500)),
                ('exrmethod', models.CharField(blank=True, max_length=500)),
                ('department', models.CharField(max_length=100)),
                ('sendtime', models.DateTimeField()),
                ('activeresult', models.CharField(blank=True, max_length=500)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtype', models.CharField(max_length=20)),
                ('boxnumber', models.IntegerField(blank=True)),
                ('samplestart', models.IntegerField(blank=True)),
                ('sampleend', models.IntegerField(blank=True)),
                ('samplenum', models.IntegerField(blank=True)),
                ('samplename', models.CharField(max_length=100)),
                ('solvent', models.CharField(max_length=100)),
                ('mass', models.FloatField()),
                ('volume', models.FloatField()),
                ('concentration', models.FloatField()),
                ('testconcentration', models.FloatField(blank=True)),
                ('department', models.CharField(max_length=100)),
                ('sendtime', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='meta',
            name='provider',
        ),
        migrations.DeleteModel(
            name='meta',
        ),
    ]
