# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181215_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='conc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='testconc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
