# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-05 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180402_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudeex',
            name='sendtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='sendtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
