# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181220_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudeex',
            name='entercol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='entervol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
