# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180405_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpdnumber', models.CharField(max_length=20)),
                ('frombact', models.CharField(max_length=20)),
                ('mass', models.FloatField()),
                ('stru', models.CharField(max_length=50)),
                ('nmr', models.CharField(max_length=100)),
                ('ms', models.CharField(max_length=100)),
                ('rot', models.CharField(max_length=100)),
                ('red', models.CharField(max_length=100)),
                ('blue', models.CharField(max_length=100)),
                ('media', models.CharField(max_length=50)),
                ('depa', models.CharField(max_length=100)),
                ('spc', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('resu', models.CharField(max_length=100)),
                ('prov', models.CharField(max_length=100)),
                ('dtime', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='crudeex',
            old_name='tetscol',
            new_name='testcol',
        ),
        migrations.AddField(
            model_name='bact',
            name='callme',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bact',
            name='danger',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bact',
            name='didv',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bact',
            name='gene',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bact',
            name='genenumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bact',
            name='getmet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bact',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bact',
            name='ill',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bact',
            name='judge',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bact',
            name='mainkey',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bact',
            name='mainuse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bact',
            name='media',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bact',
            name='mediatem',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bact',
            name='orinumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bact',
            name='prod',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bact',
            name='recadd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bact',
            name='shareme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bact',
            name='tranroute',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bact',
            name='chinesename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bact',
            name='history',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bact',
            name='othersourcenum',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
