# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180414_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bact',
            name='storetimr',
        ),
        migrations.AddField(
            model_name='bact',
            name='storetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='entertime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
