# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-29 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180416_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpd',
            name='prov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cpd',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
