# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-30 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180429_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudeex',
            name='crudenumber',
        ),
    ]
