# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_crudeex_crudenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudeex',
            name='sendtime',
            field=models.DateTimeField(),
        ),
    ]
