# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180503_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudeex',
            name='frombact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.bact'),
            preserve_default=False,
        ),
    ]
