# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-03 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_crudeex_frombact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudeex',
            name='sendtime',
            field=models.DateTimeField(blank=True),
        ),
    ]
