# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180503_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudeex',
            name='activecol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='entercol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='entertime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='entervol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='sendtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='testcol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='crudeex',
            name='testvol',
            field=models.FloatField(blank=True),
        ),
    ]
