# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-09 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_bact_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='fromcru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.crudeex'),
        ),
    ]
